name: GitHub Actions Push

run-name: '${{ github.actor }} [TESTS] Server & Client testing'

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      HOST: 0.0.0.0
      PORT: 3000
      VITE_PROTOCOL: http
      VITE_HOST: localhost
      VITE_PORT: 5000
      VITE_PORT_SERVER: 3000

    strategy:
      matrix:
        node-version: ["22.x"]

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: install dependencies
        run: pnpm install

      - name: shared test
        run: pnpm run test:shared

      - name: build server
        run: pnpm run build:s

      - name: unit server
        run: pnpm run test:s

      - name: e2e server
        run: pnpm run test:e2e:s

      - name: build client
        run: pnpm run build:c

      - name: unit client
        run: pnpm run test:c

      - name: react client
        run: pnpm run test:react

      # - name: e2e client
      #   run: pnpm run test:e2e:c
